name: OCaml Windows Segfault

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  tests:
    name: Tests

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            ocaml-compiler: 4.11.1
          - os: windows-latest
            ocaml-compiler: 4.12.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Deps
        run: opam install ocamlfind

      - name: Test
        run: opam exec -- make
